# Shopify App Configuration
# Learn more: https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d30d432207466fafa4954abc258326b7"
name = "Intellsys Connector"
handle = "intellsys-connector"
application_url = "https://conector-app.onrender.com"
embedded = true

[build]
include_config_on_deploy = true

[auth]
redirect_urls = [
  "https://conector-app.onrender.com/api/auth/callback"
]

[access_scopes]
scopes = "read_orders,read_customers,read_fulfillments,read_analytics,read_products"

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[pos]
embedded = false
